export const regionsMap: { [key: string]: string } = {
  br1: "americas",
  na1: "americas",
  la1: "americas",
  la2: "americas",
  jp1: "asia",
  kr: "asia",
  ru1: "europe",
  eun1: "europe",
  euw1: "europe",
  tr1: "europe",
  oc1: "sea",
  ph2: "sea",
  sg2: "sea",
  tw2: "sea",
  th2: "sea",
  vn2: "sea",
};
